name: tseb-workshop
channels:
    - conda-forge
    - plotly
dependencies:
    - jupyter
    - notebook
    - jupyterlab
    - jupyter-book
    - ipywidgets
    - nodejs>=20,<21
    - mystmd
    - jupyterlab-myst
    - libwebp
    - gdal
    - numpy
    - scipy
    - pandas
    - matplotlib
    - plotly
    - bokeh
    - netCDF4
    - scikit-learn
    - SALib
    - cdsapi
    - numba
    - plotly
    - pip
    - pip:
        - git+https://github.com/hectornieto/pypro4sail
        - git+https://github.com/hectornieto/pyTSEB
        - git+https://github.com/hectornieto/model_evaluation

